{% set name = "aws-cdk.cx-api" %}
{% set version = "2.103.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.cx-api-{{ version }}.tar.gz
  sha256: b478259737408da6faa6a81f17ea1512966ff9601fa9ed7a7288b5c52411b3a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >=3.7
    - aws-cdk.cloud-assembly-schema ==2.103.0
    - python-jsii >=1.89.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.cx_api
    - aws_cdk.cx_api._jsii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: Cloud executable protocol
  dev_url: https://github.com/aws/aws-cdk.git
  license: BSD-4-Clause AND Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
