{% set python_min = "3.10" %}

{% set name = "aws-cdk.cx-api" %}
{% set version = "2.218.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws_cdk_cx_api-{{ version }}.tar.gz
  sha256: fa7672d417a689a09ac24a25774398534eb03a978d6e347a7dbfbb3399d77959

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - aws-cdk.cloud-assembly-schema >=45.0.0
    - python-jsii >=1.113.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<4.3.0

test:
  imports:
    - aws_cdk.cx_api
    - aws_cdk.cx_api._jsii
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: Cloud executable protocol
  dev_url: https://github.com/aws/aws-cdk.git
  license: BSD-4-Clause AND Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
